networks:
  mofumofu-network:
    external: true
    name: mofumofu-tasks

services:
  mofumofu-backend:
    build: .
    container_name: mofumofu-backend
    env_file:
      - docker.env
    ports:
      - "8000:8000"
    networks:
      - mofumofu-network

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    env_file:
      - docker.env
    ports:
      - "7700:7700"
    networks:
      - mofumofu-network
    volumes:
      - meili_data:/meili_data