networks:
  mofumofu-network:
    external: true
    name: mofumofu-tasks

services:
  mofumofu-backend:
    build: .
    container_name: mofumofu-backend
    env_file:
      - docker.env
    ports:
      - "8000:8000"
    networks:
      - mofumofu-network